In [54]:
import pandas as pd
df = pd.read_csv("results_compiled.csv")

df = df.dropna(subset=["Perplexity"])
df = df.drop(columns=["Pseudo-Perplexity"])

In [55]:
df[['Tokens/Word', 'Perplexity', 'BPB']].corr(method='spearman')

             Tokens/Word  Perplexity       BPB
Tokens/Word     1.000000   -0.002674  0.524938
Perplexity     -0.002674    1.000000  0.745465
BPB             0.524938    0.745465  1.000000

In [43]:
metrics = ["Tokens/Word", "Perplexity", "BPB"]

pb_ref = df[df["Language"] == "PB NATIVO"][
    ["Model", "Task"] + metrics
].rename(columns={m: f"{m}_PB_NATIVO" for m in metrics})

df = df.merge(pb_ref, on=["Model", "Task"], how="left")

for metric in metrics:
    df[f"{metric} % vs PB NATIVO"] = (
        (df[metric] / df[f"{metric}_PB_NATIVO"] - 1) * 100
    )

df = df.drop(columns=[f"{m}_PB_NATIVO" for m in metrics])

df = df[df['Language'] != "PB NATIVO"]

In [44]:
df

,Model,Task,Language,Tokens/Word,Perplexity,BPB,Tokens/Word % vs PB NATIVO,Perplexity % vs PB NATIVO,BPB % vs PB NATIVO
1,Tucano,CAPACITAR,ESPANHOL,1.667410,23.555305,1.278527,26.453879,-25.496319,18.534177
2,Tucano,CAPACITAR,FRANCÊS,2.056697,19.353084,1.433445,55.976878,-38.787634,32.896859
3,Tucano,CAPACITAR,GALEGO,1.450931,73.758408,1.552995,10.036480,133.292367,43.980475
4,Tucano,CAPACITAR,INGLÊS,1.664120,25.931399,1.413014,26.204417,-17.980911,31.002645
5,Tucano,CAPACITAR,MANDARIM,1.785301,38.621955,2.263511,35.394631,22.158377,109.853532
...,...,...,...,...,...,...,...,...,...
443,Gervasio,RELATAR,GALEGO,1.660852,26.238285,1.289702,3.908595,57.568602,23.618888
444,Gervasio,RELATAR,INGLÊS,1.199963,27.506463,0.993269,-24.926206,65.184382,-4.794472
445,Gervasio,RELATAR,MANDARIM,1.930432,27.287934,1.885061,20.774430,63.872048,80.684502
446,Gervasio,RELATAR,RUSSO,2.665217,18.209563,1.593976,66.745080,9.353771,52.783759
447,Gervasio,RELATAR,ÁRABE,3.288350,25.713907,1.945512,105.730471,54.419556,86.478784

# Perplexidade

In [45]:
df.groupby("Language")["Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]]

                mean         std         50%
Language
ESPANHOL   40.280875  100.841313   16.088618
FRANCÊS     1.373780   56.328616   -9.238443
GALEGO    111.008688   77.527177  117.964308
INGLÊS     55.240798   87.147514   37.938211
MANDARIM   38.512676   91.338172   33.321881
RUSSO     121.680547  121.049536   70.297243
ÁRABE     230.473570  208.796589  189.655982

In [46]:
df.groupby("Model")["Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]]

                mean         std         50%
Model
BODE       74.384054   89.937681   54.868148
Cabrita    78.407305  125.957635   54.120057
Gemma      45.840409   98.083405   42.524831
Gervasio   58.098467   88.198449   37.287700
Qwen       64.970093  110.557043   55.421559
Sabia     197.916945  194.344020  174.008424
Tucano     78.953661  148.904580    7.100519

In [47]:
df.groupby("Task")["Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]]

                    mean         std        50%
Task
CAPACITAR      95.971981  121.783866  53.866683
COMPARTILHAR   99.423613  102.168777  73.733831
EXPLICAR       86.558768  107.623058  61.501926
EXPLORAR       80.033988  138.470963  51.874112
FAZER         -28.759058   52.981332 -40.365213
RECOMENDAR    154.987485  199.067529  87.047003
RECRIAR       115.527786  129.756023  89.222340
RELATAR        80.336505  115.883750  57.568602

# BPB

In [48]:
df.groupby("Language")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]]

                mean        std         50%
Language
ESPANHOL    6.736705  10.718018    7.914921
FRANCÊS     7.130199  16.870028    3.698930
GALEGO     32.254267  17.268899   29.708389
INGLÊS      4.820044  18.353122    4.086283
MANDARIM   72.772790  32.781475   72.292070
RUSSO      84.438891  46.927460   68.825742
ÁRABE     116.141130  47.621707  110.010384

In [49]:
df.groupby("Model")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]]

               mean        std        50%
Model
BODE      31.989869  37.807427  33.570785
Cabrita   61.034769  53.196908  42.758618
Gemma     34.718320  40.706488  28.317931
Gervasio  31.065121  38.062572  21.550503
Qwen      18.445747  28.661822  13.297464
Sabia     60.956296  54.497529  53.753967
Tucano    86.083902  65.342054  52.714652

In [50]:
df.groupby("Task")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]]

                   mean        std        50%
Task
CAPACITAR     45.139246  54.129707  31.002645
COMPARTILHAR  46.450034  44.056895  47.024652
EXPLICAR      58.176233  54.298535  46.262220
EXPLORAR      38.129475  42.923101  28.412216
FAZER         25.905684  43.332471  16.414476
RECOMENDAR    60.886179  63.268383  41.821160
RECRIAR       44.439443  45.338744  37.446339
RELATAR       51.495449  55.796632  28.166553

# Tokens/Word

In [51]:
df.groupby("Language")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]]

               mean        std        50%
Language
ESPANHOL   2.510784  14.758881  -4.059294
FRANCÊS    9.608131  23.085650  -0.584654
GALEGO     5.717135   8.559499   3.984122
INGLÊS   -10.402633  21.127482 -17.334191
MANDARIM  43.247170  47.678477  30.153507
RUSSO     71.441706  27.610165  62.221218
ÁRABE     87.287911  34.665201  84.698394

In [52]:
df.groupby("Model")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]]

               mean        std        50%
Model
BODE      15.121113  34.118248  -2.094333
Cabrita   41.753017  47.543842  19.837514
Gemma     27.362857  42.792002   3.841005
Gervasio  18.965280  37.074019   1.457119
Qwen      20.177925  37.743502   2.095699
Sabia     15.121113  34.118248  -2.094333
Tucano    70.908897  49.882913  50.362867

In [53]:
df.groupby("Task")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]]

                   mean        std        50%
Task
CAPACITAR     24.176434  48.267068  -2.264598
COMPARTILHAR  27.355149  36.536056  15.915393
EXPLICAR      41.116549  47.803912  33.531962
EXPLORAR      25.851635  41.937287   4.491587
FAZER         36.103196  48.761708  25.442112
RECOMENDAR    32.154397  48.081734  10.082661
RECRIAR       16.406830  28.442333   6.133978
RELATAR       36.161757  51.424930  19.454282

# Correlation