In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("corpora.parquet")
df.head()

,scenario,language,task,task_type,text
0,GRAMMAR SWAP,INGLÊS,CAPACITAR,ED,"Fondant / Pasta de goma\n\nEi todos, boa noite..."
1,GRAMMAR SWAP,INGLÊS,CAPACITAR,ED,"Querido Sr. Ministro,\nComo eu escrevo isso, e..."
2,GRAMMAR SWAP,INGLÊS,CAPACITAR,ED,Tens notado como diferentes teus pais têm sido...
3,GRAMMAR SWAP,INGLÊS,CAPACITAR,ED,Uma Carta Aberta\n\nNa página 2 da Folha de S....
4,GRAMMAR SWAP,INGLÊS,CAPACITAR,ED,Carta Aberta\nNazismo revelou a face mais escu...

In [3]:
df["scenario"].unique()

<ArrowStringArray>
['GRAMMAR SWAP', 'LEXICAL SWAP',  'TRANSLATION',    'PB NATIVO',
  'PB PERMUTED', 'PB CORRUPTED']
Length: 6, dtype: str

In [4]:
GS_v2 = pd.read_parquet("GRAMMAR SWAP v2.parquet")
GS_v3_en = pd.read_parquet("GRAMMAR SWAP v3_en.parquet")
GS_v3_es = pd.read_parquet("GRAMMAR SWAP v3_es.parquet")

GS_v3_en = GS_v3_en.drop(columns=["text_id", "original_text", "stanza_tokens", "words_mapping"])
GS_v3_es = GS_v3_es.drop(columns=["text_id", "original_text", "stanza_tokens", "words_mapping"])

In [5]:
new_corpora = pd.concat([df, GS_v2, GS_v3_en, GS_v3_es], ignore_index=True)
new_corpora = new_corpora.reset_index(drop=True)

new_corpora["text"] = new_corpora["text"].str.replace(r"\n+", " ", regex=True)
new_corpora

,scenario,language,task,task_type,text
0,GRAMMAR SWAP,INGLÊS,CAPACITAR,ED,"Fondant / Pasta de goma Ei todos, boa noite! E..."
1,GRAMMAR SWAP,INGLÊS,CAPACITAR,ED,"Querido Sr. Ministro, Como eu escrevo isso, eu..."
2,GRAMMAR SWAP,INGLÊS,CAPACITAR,ED,Tens notado como diferentes teus pais têm sido...
3,GRAMMAR SWAP,INGLÊS,CAPACITAR,ED,Uma Carta Aberta Na página 2 da Folha de S.Pau...
4,GRAMMAR SWAP,INGLÊS,CAPACITAR,ED,Carta Aberta Nazismo revelou a face mais escur...
...,...,...,...,...,...
1757,GRAMMAR SWAP v3,ESPANHOL,EXPLICAR,ED,1 – ¿ O que é o FIES? O FIES é um programa do ...
1758,GRAMMAR SWAP v3,ESPANHOL,EXPLICAR,FD,"ORADOR1 ¿ algum erro, senhor promotor? HABLANT..."
1759,GRAMMAR SWAP v3,ESPANHOL,EXPLICAR,FD,PEDRO no o segundo bloco tivemos a participaçã...
1760,GRAMMAR SWAP v3,ESPANHOL,EXPLICAR,FD,JOÃO ¿ mas qual é sua objeção? ¿ você crê que ...
1761,GRAMMAR SWAP v3,ESPANHOL,EXPLICAR,FD,ORADOR1 considerando que temos um grave proble...

In [6]:
new_corpora.to_parquet("corpora_v3.parquet")