In [2]:
import pandas as pd
df = pd.read_csv("lexical_swap_causalLM_results_compiled.csv")

df = df.dropna(subset=["Perplexity"])
df = df.drop(columns=["Pseudo-Perplexity"])

In [3]:
df[['Tokens/Word', 'Perplexity', 'BPB']].corr(method='spearman')

             Tokens/Word  Perplexity       BPB
Tokens/Word     1.000000   -0.025518  0.514224
Perplexity     -0.025518    1.000000  0.746274
BPB             0.514224    0.746274  1.000000

In [4]:
metrics = ["Tokens/Word", "Perplexity", "BPB"]

pb_ref = df[df["Language"] == "PB NATIVO"][
    ["Model", "Task"] + metrics
].rename(columns={m: f"{m}_PB_NATIVO" for m in metrics})

df = df.merge(pb_ref, on=["Model", "Task"], how="left")

for metric in metrics:
    df[f"{metric} % vs PB NATIVO"] = (
        (df[metric] / df[f"{metric}_PB_NATIVO"] - 1) * 100
    )

df = df.drop(columns=[f"{m}_PB_NATIVO" for m in metrics])

df = df[df['Language'] != "PB NATIVO"]

df = df.round(2)

In [5]:
df

,Model,Task,Language,Tokens/Word,Perplexity,BPB,Tokens/Word % vs PB NATIVO,Perplexity % vs PB NATIVO,BPB % vs PB NATIVO
1,BODE,CAPACITAR,ESPANHOL,1.70,20.74,1.25,-10.33,3.61,-8.50
2,BODE,CAPACITAR,FRANCÊS,1.70,23.40,1.26,-10.20,16.91,-7.74
3,BODE,CAPACITAR,GALEGO,1.77,56.82,1.76,-6.22,183.93,29.55
4,BODE,CAPACITAR,INGLÊS,1.29,40.03,1.23,-31.65,100.02,-9.67
5,BODE,CAPACITAR,MANDARIM,1.76,25.73,1.99,-6.70,28.57,46.09
...,...,...,...,...,...,...,...,...,...
443,Tucano,RELATAR,GALEGO,1.59,53.15,1.56,29.66,65.91,53.26
444,Tucano,RELATAR,INGLÊS,1.74,15.38,1.22,42.19,-51.99,20.24
445,Tucano,RELATAR,MANDARIM,2.15,47.33,2.44,75.11,47.75,140.24
446,Tucano,RELATAR,RUSSO,3.05,116.21,3.01,148.83,262.75,196.83
447,Tucano,RELATAR,ÁRABE,3.43,78.75,2.75,179.82,145.81,170.87

# Perplexidade

In [6]:
df.groupby("Language")["Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

            mean     std     50%
Language
ESPANHOL   49.78   95.08   26.21
FRANCÊS    10.90   49.28   -2.87
GALEGO    131.73   63.17  125.73
INGLÊS     79.43   86.95   70.51
MANDARIM   42.04   80.56   33.91
RUSSO     135.64  106.59  106.29
ÁRABE     240.28  184.19  199.78

In [7]:
df.groupby("Model")["Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

            mean     std     50%
Model
BODE       92.28   83.58   73.28
Cabrita    96.56  109.31   93.22
Gemma      65.09   78.22   56.79
Gervasio   73.12   83.70   44.42
Qwen       67.69  114.18   53.68
Sabia     214.58  177.71  205.13
Tucano     80.48  134.59   16.68

In [8]:
df.groupby("Task")["Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

                mean     std    50%
Task
CAPACITAR      96.24  121.86  53.87
COMPARTILHAR   99.61  101.71  73.73
EXPLICAR       86.13  107.67  61.50
EXPLORAR       87.28  108.63  52.71
FAZER          85.35   93.94  68.13
RECOMENDAR    149.12  196.33  79.64
RECRIAR       108.85  121.84  86.94
RELATAR        75.76  115.73  50.74

# BPB

In [9]:
df.groupby("Language")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

            mean    std     50%
Language
ESPANHOL    9.00   8.31    8.39
FRANCÊS    10.03  15.79    6.75
GALEGO     35.50  15.03   36.54
INGLÊS      7.37  18.38    7.15
MANDARIM   78.35  31.68   76.46
RUSSO      90.14  46.24   69.80
ÁRABE     123.67  45.68  121.34

In [10]:
df.groupby("Model")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

           mean    std    50%
Model
BODE      36.25  38.96  41.02
Cabrita   65.16  54.02  43.74
Gemma     40.13  41.17  27.06
Gervasio  36.47  38.46  20.60
Qwen      20.04  29.59  13.55
Sabia     66.68  55.50  54.66
Tucano    89.34  66.69  53.20

In [11]:
df.groupby("Task")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

               mean    std    50%
Task
CAPACITAR     45.26  54.08  31.00
COMPARTILHAR  46.57  43.96  47.02
EXPLICAR      58.18  54.25  46.26
EXPLORAR      47.36  50.21  33.72
FAZER         52.19  49.46  39.57
RECOMENDAR    61.03  63.80  43.66
RECRIAR       43.11  44.56  35.31
RELATAR       50.95  56.83  26.51

# Tokens/Word

In [12]:
df.groupby("Language")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

           mean    std    50%
Language
ESPANHOL   2.59  14.55  -4.76
FRANCÊS   10.12  23.02  -0.12
GALEGO     5.94   8.27   4.06
INGLÊS   -10.18  21.50 -16.90
MANDARIM  43.94  47.69  30.62
RUSSO     73.66  27.92  66.27
ÁRABE     89.16  34.30  85.32

In [13]:
df.groupby("Model")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

           mean    std    50%
Model
BODE      15.79  34.91  -0.88
Cabrita   42.49  48.18  22.48
Gemma     28.72  43.80   4.44
Gervasio  19.93  38.02   1.70
Qwen      21.28  38.78   2.49
Sabia     15.79  34.91  -0.88
Tucano    71.23  49.96  49.32

In [14]:
df.groupby("Task")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

               mean    std    50%
Task
CAPACITAR     24.17  48.27  -2.26
COMPARTILHAR  27.18  36.31  15.43
EXPLICAR      41.15  47.84  33.66
EXPLORAR      29.07  47.21   4.14
FAZER         39.72  48.39  27.00
RECOMENDAR    31.80  48.46   8.31
RECRIAR       17.09  29.02   6.45
RELATAR       35.79  50.64  19.07

# Correlation