In [2]:
import pandas as pd
df = pd.read_csv("lexical_swap_maskedlLM_results_compiled.csv")

df = df.dropna(subset=["Pseudo-Perplexity"])
df = df.drop(columns=["Perplexity"])

In [3]:
df[['Tokens/Word', 'Pseudo-Perplexity', 'BPB']].corr(method='spearman')

                   Tokens/Word  Pseudo-Perplexity       BPB
Tokens/Word           1.000000           0.651087  0.788571
Pseudo-Perplexity     0.651087           1.000000  0.951163
BPB                   0.788571           0.951163  1.000000

In [4]:
metrics = ["Tokens/Word", "Pseudo-Perplexity", "BPB"]

pb_ref = df[df["Language"] == "PB NATIVO"][
    ["Model", "Task"] + metrics
].rename(columns={m: f"{m}_PB_NATIVO" for m in metrics})

df = df.merge(pb_ref, on=["Model", "Task"], how="left")

for metric in metrics:
    df[f"{metric} % vs PB NATIVO"] = (
        (df[metric] / df[f"{metric}_PB_NATIVO"] - 1) * 100
    )

df = df.drop(columns=[f"{m}_PB_NATIVO" for m in metrics])

df = df[df['Language'] != "PB NATIVO"]

df = df.round(2)

In [ ]:
df

,Model,Task,Language,Tokens/Word,Perplexity,BPB,Tokens/Word % vs PB NATIVO,Perplexity % vs PB NATIVO,BPB % vs PB NATIVO
1,BODE,CAPACITAR,ESPANHOL,1.70,20.74,1.25,-10.33,3.61,-8.50
2,BODE,CAPACITAR,FRANCÊS,1.70,23.40,1.26,-10.20,16.91,-7.74
3,BODE,CAPACITAR,GALEGO,1.77,56.82,1.76,-6.22,183.93,29.55
4,BODE,CAPACITAR,INGLÊS,1.29,40.03,1.23,-31.65,100.02,-9.67
5,BODE,CAPACITAR,MANDARIM,1.76,25.73,1.99,-6.70,28.57,46.09
...,...,...,...,...,...,...,...,...,...
443,Tucano,RELATAR,GALEGO,1.59,53.15,1.56,29.66,65.91,53.26
444,Tucano,RELATAR,INGLÊS,1.74,15.38,1.22,42.19,-51.99,20.24
445,Tucano,RELATAR,MANDARIM,2.15,47.33,2.44,75.11,47.75,140.24
446,Tucano,RELATAR,RUSSO,3.05,116.21,3.01,148.83,262.75,196.83
447,Tucano,RELATAR,ÁRABE,3.43,78.75,2.75,179.82,145.81,170.87

# Perplexidade

In [6]:
df.groupby("Language")["Pseudo-Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

             mean      std      50%
Language
ESPANHOL   148.63   139.50   123.09
FRANCÊS    682.53   637.51   659.74
GALEGO     154.32   116.79   146.17
INGLÊS     446.89   510.61   233.66
MANDARIM  1024.14  1030.68   669.19
RUSSO     2926.50  2273.34  2262.16
ÁRABE     2359.52  3548.46  1313.68

In [7]:
df.groupby("Model")["Pseudo-Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

                   mean      std      50%
Model
Albertina100m   1839.04  1775.37  1212.78
Albertina900m   2000.64  2375.43   826.66
BERTimbau        819.99   800.86   622.17
BERTimbauLarge  1464.74  3205.01   653.62
mBERT            118.83   177.07    43.69
xlm              393.21   502.78    96.39

In [8]:
df.groupby("Task")["Pseudo-Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

                 mean      std     50%
Task
CAPACITAR     1099.94  1623.26  398.29
COMPARTILHAR   759.50  1036.39  315.30
EXPLICAR       893.50  1383.13  325.96
EXPLORAR      1216.42  1698.81  480.48
FAZER          929.80  1405.11  433.59
RECOMENDAR    1466.31  2026.85  666.06
RECRIAR        771.51   930.27  429.71
RELATAR       1711.63  3829.57  449.40

# BPB

In [9]:
df.groupby("Language")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

            mean     std     50%
Language
ESPANHOL  112.69   94.08  120.94
FRANCÊS   235.26  184.89  284.13
GALEGO    118.35   93.51  111.47
INGLÊS    153.03   96.81  189.48
MANDARIM  421.27  230.31  427.42
RUSSO     542.38  300.87  523.56
ÁRABE     526.07  296.15  452.67

In [10]:
df.groupby("Model")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

                  mean     std     50%
Model
Albertina100m   444.65  251.29  365.30
Albertina900m   488.92  343.08  355.05
BERTimbau       310.86  172.23  297.47
BERTimbauLarge  368.77  235.56  332.28
mBERT            57.84   74.16   17.92
xlm             136.72  139.97   48.40

In [11]:
df.groupby("Task")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

                mean     std     50%
Task
CAPACITAR     320.59  286.50  242.51
COMPARTILHAR  201.28  152.71  176.10
EXPLICAR      332.18  286.93  271.34
EXPLORAR      278.81  226.86  214.30
FAZER         293.67  242.24  204.40
RECOMENDAR    382.74  333.44  286.32
RECRIAR       220.44  166.15  193.99
RELATAR       380.64  349.49  293.62

# Tokens/Word

In [12]:
df.groupby("Language")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

           mean    std    50%
Language
ESPANHOL   6.11  15.88  -2.34
FRANCÊS   17.72  26.60   3.30
GALEGO     5.62  10.46   0.74
INGLÊS     1.61  34.04  -5.04
MANDARIM  43.27  46.78  36.09
RUSSO     74.85  37.21  68.44
ÁRABE     90.27  43.50  79.73

In [13]:
df.groupby("Model")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

                 mean    std    50%
Model
Albertina100m    6.71  31.53  -4.19
Albertina900m    9.90  32.14  -1.72
BERTimbau       66.62  47.30  50.66
BERTimbauLarge  66.62  47.30  50.66
mBERT           24.19  38.91   1.53
xlm             31.20  41.95   9.48

In [14]:
df.groupby("Task")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

               mean    std    50%
Task
CAPACITAR     27.71  50.72   7.66
COMPARTILHAR  25.92  31.45  26.86
EXPLICAR      43.90  48.15  30.99
EXPLORAR      34.95  52.50  22.13
FAZER         44.27  49.55  35.49
RECOMENDAR    35.58  51.72  23.32
RECRIAR       21.84  31.52  20.12
RELATAR       39.46  52.06  29.97

# Correlation