In [9]:
import pandas as pd
df = pd.read_csv("translation_maskedLM_results_compiled.csv")

df = df.dropna(subset=["Pseudo-Perplexity"])
df = df.drop(columns=["Perplexity"])

In [11]:
df[['Tokens/Word', 'Pseudo-Perplexity', 'BPB']].corr(method='spearman')

                   Tokens/Word  Pseudo-Perplexity       BPB
Tokens/Word           1.000000           0.709766  0.795844
Pseudo-Perplexity     0.709766           1.000000  0.970870
BPB                   0.795844           0.970870  1.000000

In [12]:
metrics = ["Tokens/Word", "Pseudo-Perplexity", "BPB"]

pb_ref = df[df["Language"] == "PB NATIVO"][
    ["Model", "Task"] + metrics
].rename(columns={m: f"{m}_PB_NATIVO" for m in metrics})

df = df.merge(pb_ref, on=["Model", "Task"], how="left")

for metric in metrics:
    df[f"{metric} % vs PB NATIVO"] = (
        (df[metric] / df[f"{metric}_PB_NATIVO"] - 1) * 100
    )

df = df.drop(columns=[f"{m}_PB_NATIVO" for m in metrics])

df = df[df['Language'] != "PB NATIVO"]

df = df.round(2)

In [13]:
df

,Model,Task,Language,Tokens/Word,Pseudo-Perplexity,BPB,Tokens/Word % vs PB NATIVO,Pseudo-Perplexity % vs PB NATIVO,BPB % vs PB NATIVO
1,Albertina100m,CAPACITAR,ESPANHOL,2.11,8.65,1.05,-4.14,386.38,270.34
2,Albertina100m,CAPACITAR,FRANCÊS,2.10,32.53,1.74,-4.40,1729.40,514.14
3,Albertina100m,CAPACITAR,GALEGO,2.14,9.15,1.09,-2.67,414.80,285.53
4,Albertina100m,CAPACITAR,INGLÊS,1.28,11.64,0.79,-41.79,554.59,176.41
5,Albertina100m,CAPACITAR,MANDARIM,1.75,30.11,2.08,-20.39,1593.49,630.81
...,...,...,...,...,...,...,...,...,...
379,xlm,RELATAR,GALEGO,1.47,3.56,0.42,12.43,-30.28,-10.28
380,xlm,RELATAR,INGLÊS,1.36,3.15,0.39,3.71,-38.21,-17.81
381,xlm,RELATAR,MANDARIM,3.43,20.75,2.02,161.71,306.69,326.35
382,xlm,RELATAR,RUSSO,2.60,57.49,1.95,98.29,1026.56,312.67
383,xlm,RELATAR,ÁRABE,3.36,28.43,1.83,156.29,457.18,286.52

# Perplexidade

In [14]:
df.groupby("Language")["Pseudo-Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

             mean      std      50%
Language
ESPANHOL   134.22   158.66   123.74
FRANCÊS    593.05   578.95   633.00
GALEGO     167.17   162.16   152.98
INGLÊS     212.76   220.02   207.37
MANDARIM   896.32   699.16   620.90
RUSSO     3709.07  3058.07  2731.18
ÁRABE     2289.20  3159.46  1332.70

In [15]:
df.groupby("Model")["Pseudo-Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

                   mean      std      50%
Model
Albertina100m   1840.43  2102.92  1023.56
Albertina900m   2138.26  2980.44   592.95
BERTimbau        926.95  1106.57   569.88
BERTimbauLarge  1492.29  2947.91   628.55
mBERT             87.10   169.61   -14.84
xlm              373.67   577.77   -21.48

In [16]:
df.groupby("Task")["Pseudo-Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

                 mean      std     50%
Task
CAPACITAR     1469.33  2372.21  465.66
COMPARTILHAR   909.36  1323.41  420.02
EXPLICAR      1060.00  1641.92  400.67
EXPLORAR      1075.36  1828.96  393.46
FAZER         1209.69  2352.51  366.20
RECOMENDAR    1207.58  1977.98  478.48
RECRIAR        691.08   864.69  375.54
RELATAR       1522.53  3472.40  349.28

# BPB

In [17]:
df.groupby("Language")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

            mean     std     50%
Language
ESPANHOL  105.44  104.86  119.04
FRANCÊS   222.43  198.40  286.26
GALEGO    125.60  112.87  125.68
INGLÊS    114.20  107.17  127.54
MANDARIM  433.14  247.27  382.05
RUSSO     582.72  322.96  570.23
ÁRABE     528.15  286.04  479.26

In [18]:
df.groupby("Model")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

                  mean     std     50%
Model
Albertina100m   448.79  261.98  358.54
Albertina900m   491.07  368.64  359.70
BERTimbau       325.07  183.17  284.06
BERTimbauLarge  381.35  249.37  316.53
mBERT            48.29   82.43   -4.62
xlm             115.43  165.23   -6.88

In [19]:
df.groupby("Task")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

                mean     std     50%
Task
CAPACITAR     330.58  314.37  277.50
COMPARTILHAR  198.81  164.53  185.96
EXPLICAR      333.77  302.87  287.13
EXPLORAR      280.41  254.79  233.62
FAZER         314.39  286.87  216.82
RECOMENDAR    360.04  330.69  290.76
RECRIAR       213.12  167.57  185.21
RELATAR       382.21  371.14  288.50

# Tokens/Word

In [20]:
df.groupby("Language")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

            mean    std    50%
Language
ESPANHOL   10.09  16.37   2.45
FRANCÊS    20.30  27.00   8.19
GALEGO     11.40  12.36   5.56
INGLÊS      2.27  35.45  -4.04
MANDARIM   49.27  65.42  27.09
RUSSO      83.17  40.33  72.87
ÁRABE     103.92  61.67  93.92

In [21]:
df.groupby("Model")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

                 mean    std    50%
Model
Albertina100m   10.75  39.81  -1.39
Albertina900m   14.37  39.52   1.08
BERTimbau       73.92  57.81  52.18
BERTimbauLarge  73.92  57.81  52.18
mBERT           30.22  47.03   5.74
xlm             37.16  51.64   9.16

In [22]:
df.groupby("Task")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

               mean    std    50%
Task
CAPACITAR     22.70  37.89  18.76
COMPARTILHAR  11.78  25.69   5.22
EXPLICAR      29.21  39.11  18.56
EXPLORAR      57.67  60.66  47.46
FAZER         57.42  64.67  41.85
RECOMENDAR    45.70  65.80  29.20
RECRIAR       29.09  42.17  24.21
RELATAR       66.90  68.68  53.48