In [1]:
import pandas as pd
df = pd.read_csv("translation_causalLM_results_compiled.csv")

df = df.dropna(subset=["Perplexity"])
df = df.drop(columns=["Pseudo-Perplexity"])

In [2]:
df[['Tokens/Word', 'Perplexity', 'BPB']].corr(method='spearman')

             Tokens/Word  Perplexity       BPB
Tokens/Word     1.000000    0.103390  0.509181
Perplexity      0.103390    1.000000  0.846741
BPB             0.509181    0.846741  1.000000

In [3]:
metrics = ["Tokens/Word", "Perplexity", "BPB"]

pb_ref = df[df["Language"] == "PB NATIVO"][
    ["Model", "Task"] + metrics
].rename(columns={m: f"{m}_PB_NATIVO" for m in metrics})

df = df.merge(pb_ref, on=["Model", "Task"], how="left")

for metric in metrics:
    df[f"{metric} % vs PB NATIVO"] = (
        (df[metric] / df[f"{metric}_PB_NATIVO"] - 1) * 100
    )

df = df.drop(columns=[f"{m}_PB_NATIVO" for m in metrics])

df = df[df['Language'] != "PB NATIVO"]

df = df.round(2)

In [4]:
df

,Model,Task,Language,Tokens/Word,Perplexity,BPB,Tokens/Word % vs PB NATIVO,Perplexity % vs PB NATIVO,BPB % vs PB NATIVO
1,BODE,CAPACITAR,ESPANHOL,1.79,11.04,1.02,-5.15,-44.85,-25.40
2,BODE,CAPACITAR,FRANCÊS,1.78,9.80,0.97,-6.06,-51.05,-29.13
3,BODE,CAPACITAR,GALEGO,1.92,51.61,1.79,1.73,157.87,31.66
4,BODE,CAPACITAR,INGLÊS,1.41,12.01,0.87,-25.42,-39.98,-36.11
5,BODE,CAPACITAR,MANDARIM,1.75,32.58,2.12,-7.65,62.82,55.68
...,...,...,...,...,...,...,...,...,...
443,Tucano,RELATAR,GALEGO,1.73,49.71,1.55,41.40,55.18,52.66
444,Tucano,RELATAR,INGLÊS,1.83,12.68,1.16,49.56,-60.42,14.57
445,Tucano,RELATAR,MANDARIM,3.88,25.94,2.47,216.39,-19.03,143.12
446,Tucano,RELATAR,RUSSO,3.30,108.06,2.96,168.91,237.30,191.71
447,Tucano,RELATAR,ÁRABE,3.85,68.82,2.72,213.86,114.81,168.08

# Perplexidade

In [5]:
df.groupby("Language")["Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

            mean     std     50%
Language
ESPANHOL   -5.55   64.58  -30.38
FRANCÊS   -44.33   21.22  -47.02
GALEGO    103.72   75.56   98.26
INGLÊS    -28.77   33.97  -27.32
MANDARIM   38.82   79.30   41.46
RUSSO     145.18  160.36  105.20
ÁRABE     167.38  152.54  127.58

In [6]:
df.groupby("Model")["Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

            mean     std     50%
Model
BODE       41.29   82.69   25.77
Cabrita    68.44  121.43   21.74
Gemma       2.58   73.08   -7.22
Gervasio    6.81   57.22   -5.18
Qwen       31.32   98.51    4.18
Sabia     154.02  174.64  146.98
Tucano     71.99  157.20   26.54

In [7]:
df.groupby("Task")["Perplexity % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

               mean     std    50%
Task
CAPACITAR     63.14  138.65  15.44
COMPARTILHAR  96.32  166.41  33.17
EXPLICAR      68.16  123.07  21.53
EXPLORAR      24.70   93.46 -11.31
FAZER         40.27  146.66 -14.14
RECOMENDAR    48.38  104.00  13.76
RECRIAR       58.36   95.66  35.27
RELATAR       30.90  108.14  -6.38

# BPB

In [8]:
df.groupby("Language")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

            mean    std    50%
Language
ESPANHOL   -1.98  13.03  -1.61
FRANCÊS    -7.45  16.68 -13.64
GALEGO     34.28  18.18  38.56
INGLÊS    -15.41  15.51 -18.03
MANDARIM   77.97  33.09  76.18
RUSSO      89.56  51.65  67.41
ÁRABE     110.36  40.39  99.98

In [9]:
df.groupby("Model")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

           mean    std    50%
Model
BODE      25.19  43.67  38.38
Cabrita   58.67  59.04  44.78
Gemma     26.43  46.06  19.56
Gervasio  20.03  38.79  11.34
Qwen      17.73  32.95  14.44
Sabia     54.87  59.32  56.38
Tucano    84.42  71.65  51.75

In [10]:
df.groupby("Task")["BPB % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

               mean    std    50%
Task
CAPACITAR     36.28  60.88  17.05
COMPARTILHAR  39.44  54.37  32.79
EXPLICAR      51.16  62.35  34.32
EXPLORAR      36.45  55.91  25.20
FAZER         41.67  57.33  31.77
RECOMENDAR    44.56  59.03  27.42
RECRIAR       34.46  44.32  28.95
RELATAR       44.36  57.74  33.94

# Tokens/Word

In [11]:
df.groupby("Language")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

            mean    std     50%
Language
ESPANHOL    6.69  14.07    0.90
FRANCÊS    12.55  22.64    2.08
GALEGO     11.43   9.00    9.14
INGLÊS     -9.78  21.37  -18.94
MANDARIM   50.20  67.64   15.18
RUSSO      81.80  29.39   74.07
ÁRABE     104.93  57.25  103.12

In [12]:
df.groupby("Model")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

           mean    std    50%
Model
BODE      20.96  42.78   0.90
Cabrita   49.47  62.38  23.33
Gemma     35.53  53.01   7.44
Gervasio  26.01  48.22   4.38
Qwen      26.67  46.69   4.36
Sabia     20.96  42.78   0.90
Tucano    78.22  61.71  46.88

In [13]:
df.groupby("Task")["Tokens/Word % vs PB NATIVO"].describe()[["mean", "std", "50%"]].round(2)

               mean    std    50%
Task
CAPACITAR     20.31  35.67   4.30
COMPARTILHAR  11.88  27.33   2.83
EXPLICAR      26.88  36.35  10.18
EXPLORAR      51.09  58.51  29.69
FAZER         54.99  67.55  27.88
RECOMENDAR    43.39  67.28   7.91
RECRIAR       23.78  39.10   6.98
RELATAR       62.34  67.88  41.40